### ISSUE TITLE
Application is Not Run

### ISSUE THREAD

**Issue by NageshRaykar** [dlclark/metaphone3#1]
I have Imported this Application in Eclipse IDE Suppose I am running this but i am getting only Error:0 Exception. please help

**Comment by dlclark** [comment]
It sounds like you’re trying to run the reference Java version of the code—this library is for Go and only has the java code as a reference in a non-runnable state. 

If you’re trying to run the Go code you’ll need to write your own package main and import the library to use it.

**Comment by NageshRaykar** [comment]
hi dlclark,

Thank you for your quick response, its really appreciated. 
I will try the same , if i am facing any issue i will ask you.

Is this applicable for training dataset?
Suppose we are trying to test the dataset in currently your algorithm we are not getting any path:  we are getting only these line for line by line reading line   (but Attrib,find.go,metaphone3.go,metaphone3,metaphone3_utils_test.go,metaphone3_words_test.go ) we are unable to understand.  

****Can you help me sir.**** 
[metaphone3.txt](https://github.com/dlclark/metaphone3/files/4916507/metaphone3.txt)
